# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('is_admin', models.NullBooleanField()),
                ('is_approved', models.NullBooleanField()),
            ],
        ),
    ]
