# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
