# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180310_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stage_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
