# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-16 10:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_person_stage_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='storage',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
