# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_person_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='storage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
