# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-18 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person_is_score_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_score_manager',
            field=models.BooleanField(default=False),
        ),
    ]
