"""
Django settings for audrey project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
#import telepot
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'juu^jg=5cnz19z5k85wl(2&8&b8z5d-!u)tf8ixwhcfag9o&@!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'stages.apps.StagesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'audrey.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'audrey.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

BOT_TOKEN = str('462615061:AAHqdSi1rMiMpQ9vEpVn3COOkrnSbHrfWm4')

#bot = telepot.Bot(BOT_TOKEN)

SUPERADMIN = '47237387'

STAGES= [

    ##########################
    ###Normal User Function###
    ##########################462615061:AAHqdSi1rMiMpQ9vEpVn3COOkrnSbHrfWm4
    #Conversation: authorization
   {
      'command_pattern_check':'command == "/signup"',
      'stage_code':'auth'
   },

   #Conversation: get master list of scores
   {
      'command_pattern_check':'command == "/listscores"',
      'stage_code':'listScores'
   },

   #Conversation: get score by code
   {
      'command_pattern_check':'command[:9] == "/songcode"',
      'stage_code':'songCode'
   },

   #Conversation: get score by song name
   {  
      'command_pattern_check':'command == "/scorebyname"',
      'stage_code':'scoreByName'
   },

   #Conversation: get score by lyrics
   {
      'command_pattern_check':'command[:14] == "/scorebylyrics"',
      'stage_code':'scoreByLyrics'
   },

   #Conversation: get lyrics by song name

   #Conversation: get lyrics by part of the lyrics

   #Conversation: cancel
   {
      'command_pattern_check':'command == "/cancel"',
      'stage_code':'cancel'
   },

   #Conversation: change language
   {
      'command_pattern_check':'command == "/changelang"',
      'stage_code':'changeLang'
   },

    #########################
    ###Admin User Function###
    #########################

    #Conversation: user approval  
   {
      'command_pattern_check':'command[:8] == "/approve"',
      'stage_code':'approve'
   },

   #Conversation: list users
   {
      'command_pattern_check':'command == "/listusers"',
      'stage_code':'listUsers'
   },

   #Conversation: rename user
    {
      'command_pattern_check':'command == "/renameuser"',
      'stage_code':'renameUser'
   },

   #Conversation: list admin users
   {
      'command_pattern_check':'command == "/listadmins"',
      'stage_code':'listAdmins'
   },

   #Conversation: list score manager users
   {
      'command_pattern_check':'command == "/listscoremanagers"',
      'stage_code':'listScoreManagers'
   },

   #Conversation: set user as admin
   {
      'command_pattern_check':'command == "/setadmin"',
      'stage_code':'setAdmin'
   },

   #Conversation: unset admin
   {
      'command_pattern_check':'command == "/unsetadmin"',
      'stage_code':'unsetAdmin'
   },

   #Conversation: set user as score manager
   {
      'command_pattern_check':'command == "/setscoremanager"',
      'stage_code':'setScoreManager'
   },

   #Conversation: unset score manager
   {
      'command_pattern_check':'command == "/unsetscoremanager"',
      'stage_code':'unsetScoreManager'
   },

   #Conversation: delete user
   {
      'command_pattern_check':'command == "/deleteuser"',
      'stage_code':'deleteUser'
   },

   #Conversation: List Admin functions
   {
      'command_pattern_check':'command == "/adminmenu"',
      'stage_code':'listAdminFunctions'
   },

    #Conversation: List Score Manager functions
   {
      'command_pattern_check':'command == "/scoremgrmenu"',
      'stage_code':'listScoreManagerFunctions'
   },
   
   #Conversation: Announcement
   {
      'command_pattern_check':'command == "/announcement"',
      'stage_code':'announcement'
   },


   #Conversation: upload score
    {
      'command_pattern_check':'command == "/uploadscore"',
      'stage_code':'uploadScore'
    }
]

