# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.CharField(max_length=200)),
                ('command_pattern_check', models.CharField(max_length=200)),
                ('function_call', models.CharField(max_length=200)),
                ('is_first', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=200)),
                ('stage_code', models.CharField(max_length=200)),
            ],
        ),
    ]
