# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_auto_20180310_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
    ]
