# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='path',
            new_name='file_path',
        ),
    ]
