# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-15 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_delete_userprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
