# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stages', '0007_delete_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=200)),
            ],
        ),
    ]
