# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='stroke',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
